h2:
  username: root
  password: 123
  db:
    type: mem
    name: library
    mode: MYSQL
  console:
    enabled: true

mail:
  from: mail@library-api.com
  protocol: smtp
  host: smtp.mailtrap.io
  port: 2525
  username: 5b1b1b1b1b1b1b1b1b
  password: 5b1b1b1b1b1b1b1b1b
  smtp:
    auth.enable: true
    starttls.enable: true

server:
  port: 8083
  servlet:
    context-path: /api
  compression:
    enabled: true
    mime-types: text/html,text/xml,text/plain,text/css,text/javascript,application/javascript,application/json # Comma-separated list of MIME types that should be compressed.
    min-response-size: 1024
  undertow:
    threads:
      worker: 64
      io: 4

spring:
  application:
    name: library-api
  threads:
    virtual:
      enabled: true
  datasource:
    url: jdbc:h2:${h2.db.type}:${h2.db.name};MODE=${h2.db.mode};DATABASE_TO_LOWER=TRUE;
    username: ${h2.username}
    password: ${h2.password}
    driver-class-name: org.h2.Driver
    hikari:
      auto-commit: false
      connection-timeout: 250
      max-lifetime: 600000
      maximum-pool-size: 20
      minimum-idle: 10
      pool-name: master
  jpa:
    open-in-view: false
    show-sql: false
    hibernate:
      ddl-auto: update
    properties:
      "[hibernate.generate_statistics]": false
      "[hibernate.connection.provider_disables_autocommit]": true
  h2:
    console:
      enabled: ${h2.console.enabled}
      path: /h2-console
  mail:
    protocol: ${mail.protocol}
    host: ${mail.host}
    port: ${mail.port}
    username: ${mail.username}
    password: ${mail.password}
    properties:
      mail:
        smtp:
          auth: ${mail.smtp.auth.enable}
          starttls:
            enable: ${mail.smtp.starttls.enable}